import "./globals.css";


export const metadata = {
  title: "Ernesto-todo-manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          header
        </header>

        {children}
        
        <footer>
          footer
        </footer>
      </body>
    </html>
  );
}
